const players = [
  { id: "飞天大蟑螂", professions: ["嗟夫刀法", "八方风雷枪"] },
  { id: "鬼公仔", professions: ["嗟夫刀法", "泥犁三垢"] },
  { id: "震霸天", professions: ["积矩九剑", "九曲惊神枪"] },
  { id: "风千杨", professions: ["十方破阵", "嗟夫刀法"] },
  { id: "以年", professions: ["嗟夫刀法", "八方风雷枪"] },
  { id: "费曼", professions: ["无名剑法", "无名枪法"] },
  { id: "常伴明月", professions: ["嗟夫刀法", "青山执笔"] },
  { id: "斩红郎", professions: ["嗟夫刀法", "无名剑法"] },
  { id: "沈晔行", professions: ["无名剑法", "无名枪法"] },
  { id: "秦兆丰", professions: ["无名剑法", "无名枪法"] },
  { id: "王荒炎", professions: ["无名剑法", "无名枪法"] },
  { id: "涂慕辞", professions: ["无名剑法", "无名枪法"] },
  { id: "寂渴", professions: ["无名剑法", "无名枪法"] },
  { id: "穗穗平安", professions: ["无名剑法", "无名枪法"] },
  { id: "柿水", professions: ["无名剑法", "无名枪法"] },
  { id: "宛有", professions: ["无名剑法", "无名枪法"] },
  { id: "攸风", professions: ["无名剑法", "无名枪法"] },
  { id: "晏极", professions: ["无名剑法", "无名枪法"] },
  { id: "三石", professions: ["天志垂象", "千机索天"] },
  { id: "起风了", professions: ["无名剑法", "无名枪法"] },
  { id: "好婉", professions: ["醉梦游春", "粟子行云"] },
  { id: "撼山", professions: ["无名剑法", "无名枪法"] },
  { id: "柳雾轻烟", professions: ["醉梦游春", "粟子行云"] },
  { id: "卫君肃", professions: ["积矩九剑", "九曲惊神枪"] },
  { id: "晴翼", professions: ["醉梦游春", "粟子行云"] },
  { id: "十五重逢", professions: ["积矩九剑", "九曲惊神枪"] },
  { id: "羽杉", professions: ["积矩九剑", "九曲惊神枪"] },
  { id: "青未觉", professions: ["积矩九剑", "九曲惊神枪"] },
  { id: "佟生战兔", professions: ["积矩九剑", "九曲惊神枪"] },
  { id: "水中月天上光", professions: ["积矩九剑", "九曲惊神枪"] },
  { id: "斩秋风", professions: ["嗟夫刀法"] },
  { id: "今早不想起", professions: ["积矩九剑", "九曲惊神枪"] },
  { id: "薛星辰", professions: ["明川药典", "千香引魂蛊"] },
  { id: "安平君祝", professions: ["明川药典", "千香引魂蛊"] },
  { id: "叶音绮", professions: ["明川药典", "千香引魂蛊"] },
  { id: "柴喵", professions: ["明川药典", "千香引魂蛊"] },
  { id: "禄歆", professions: ["明川药典", "千香引魂蛊"] },
  { id: "墨灵渊", professions: ["明川药典", "千香引魂蛊"] },
  { id: "昭昭如曌", professions: ["明川药典", "千香引魂蛊"] },
  { id: "林镜流", professions: ["明川药典", "千香引魂蛊"] },
  { id: "寒沉烟", professions: ["明川药典", "千香引魂蛊"] },
  { id: "顾镜澄", professions: ["明川药典", "千香引魂蛊"] },
  { id: "青城山土豆精", professions: ["明川药典", "千香引魂蛊"] },
  { id: "南宫淮澜", professions: ["明川药典", "千香引魂蛊"] },
  { id: "江沄涧", professions: ["明川药典", "千香引魂蛊"] },
  { id: "百寂生", professions: ["醉梦游春", "粟子行云"] }
];

console.log(JSON.stringify(players, null, 2));
